let
    Source = Csv.Document(File.Contents("C:\Users\User\Downloads\dirty_sales_data.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cust   name", type text}, {"ORDER.DATE", type text}, {"$amount", type text}, {"qty", Int64.Type}, {"STATUS", type text}, {"category ", type text}, {"duplicate_id", Int64.Type}, {"discount", type number}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"cust   name", "CustomerName"}, {"ORDER.DATE", "OrderDate"}, {"$amount", "Amount"}, {"qty", "Quantity"}, {"STATUS", "Status"}, {"category ", "Category"}, {"duplicate_id", "DuplicateID"}, {"discount", "Discount"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","NULL","0",Replacer.ReplaceText,{"Amount"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","","0",Replacer.ReplaceValue,{"Amount"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value1",{{"Amount", type number}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type1",null,0,Replacer.ReplaceValue,{"Quantity"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",null,0,Replacer.ReplaceValue,{"Discount"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value3",{{"Quantity", Int64.Type}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type2", {"CustomerName"}),
    #"Removed Alternate Rows" = Table.AlternateRows(#"Removed Duplicates",7,1,17),
    #"Replaced Value4" = Table.ReplaceValue(#"Removed Alternate Rows","2024-01-16","01/16/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","15-01-2024","01/15/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","2024/01/18","01/18/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","19-Jan-2024","01/19/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","01-21-2024","01/21/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","2024-01-22","01/22/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","01-26-2024","01/26/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","2024/01/27","01/27/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","24/01/2024","01/24/2024",Replacer.ReplaceText,{"OrderDate"}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Replaced Value12",{{"CustomerName", Text.Proper, type text}}),
    #"Lowercased Text" = Table.TransformColumns(#"Capitalized Each Word",{{"Status", Text.Lower, type text}}),
    #"Capitalized Each Word1" = Table.TransformColumns(#"Lowercased Text",{{"Category", Text.Proper, type text}}),
    #"Added Custom" = Table.AddColumn(#"Capitalized Each Word1", "TotalAmount", each [Quantity] * [Amount] * (1 - [Discount])),
    #"Inserted Parsed Date" = Table.AddColumn(#"Added Custom", "Parse", each Date.From(DateTimeZone.From([OrderDate])), type date),
    #"Inserted Year" = Table.AddColumn(#"Inserted Parsed Date", "Year", each Date.Year([Parse]), Int64.Type),
    #"Removed Columns" = Table.RemoveColumns(#"Inserted Year",{"Parse"}),
    #"Added Conditional Column" = Table.AddColumn(#"Removed Columns", "IsCompleted", each if [Status] = "completed" then true else false)
in
    #"Added Conditional Column"